version: '3.7'

networks:
  default:
    name: access-control-network

services:
  google-home:
    image: propuskator/google-home-integration:release
    container_name: google-home
    logging: &default-logging
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    restart: always
    environment:
      - APP_PORT=${GOOGLE_HOME_APP_PORT:-3000}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SESSION_COOKIE_SECRET=${ACCESS_TOKEN_SECRET}
      - MQTT_USER=${MQTT_ROOT_USERNAME}
      - MQTT_PASS=${MQTT_ROOT_PASSWORD}
      - MQTT_URI=${MQTT_URI}
      - API_URL=${API_URL}
      - WAIT_HOSTS=${BACKEND_HOST:-access-backend}:${PORT:-8000}
    volumes:
      - ${ROOT_DIR}/system/google-home/config/google:/app/config/google
